add user UI
armanmasangkay/watersystem pull request #6
Opened 2021-02-08 03:32 UTC by darksidebug

2021-02-12 03:17 UTC, armanmasangkay requested changes

2021-02-12 03:17 UTC, armanmasangkay commented on resources/views/layout/main_layout.blade.php
> +            @yield('addUser_content')
It would be maintainable if we only use one @yield

we can use @yield('content') instead for all contents

2021-02-12 03:17 UTC, armanmasangkay commented on resources/views/pages/add-user.blade.php
> +@section('addUser_content')
If we only have one @yield('content') it would be easy for use to reuse templates

2021-02-15 02:46 UTC, darksidebug commented
Changes done...

2021-02-15 02:46 UTC, closed without merging